### ISSUE TITLE
Maven artifact

### ISSUE THREAD

**Issue by sishbi** [martinwithaar/Encryptor4j#1]
Hello Martin,
We would like to consume your library as part of our product, would you be able to publish it as a Maven artifact?
I should be able to create a pull request with the necessary changes to help you.
Thanks, Simon.

**Comment by sishbi** [comment]
I have done the necessary changes to the build.gradle to include maven repository publishing (patch to follow).
If this component is going to be available in Maven central then it needs publishing to Sonatype OSSRH, following this guide:
http://central.sonatype.org/pages/ossrh-guide.html

**Comment by sishbi** [comment]
I have made the necessary changes to allow this to be published to Maven Central, via Sonatype OSS
and during this process went ahead and published it:
https://oss.sonatype.org/#nexus-search;quick~encryptor4j

I have created a pull request #2 which I would like you to accept.

**Comment by martinwithaar** [comment]
I would like to apologize for my late response. Hopefully everything is working out at your end right now!

**Comment by martinwithaar** [comment]
Note: I have published the library on Maven Central under a different group. http://search.maven.org/#artifactdetails%7Corg.encryptor4j%7Cencryptor4j%7C0.1%7Cjar

**Comment by sishbi** [comment]
Actually, we changed our project so that we no longer required this library.
Thanks for responding anyway.
I guess if the library is available on Maven central then as long as the README.md lists the Maven GAV coordinates then everything is good.
