### ISSUE TITLE
PBKDF2WithHmacSHA256 SecretKeyFactory not available

### ISSUE THREAD

**Issue by dri94** [martinwithaar/Encryptor4j#4]
I am getting this when i am running this on android with proguard. The full error is 

```
Caused by: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: PBKDF2WithHmacSHA256 SecretKeyFactory not available
	at org.encryptor4j.factory.AbsKeyFactory.keyFromPassword(AbsKeyFactory.java:94)
	at org.encryptor4j.util.TextEncryptor.<init>(TextEncryptor.java:49)
```

**Comment by MichalStranik** [comment]
I am getting this without proguard on Android API 19.

**Comment by dri94** [comment]
It seems to have to do with the java version on different phones. It will work fine on the pixel, but cause an error on the S7.

**Comment by thanhthang90** [comment]
Samsung A7100 android 6.0.1, LG f260s android 19 similar error as above. 
`SecretKeyFactory PBKDF2WithHmacSHA256 implementation not found`

**Comment by martinwithaar** [comment]
These types of errors are unfortunately beyond my control. Device manufacturers decide for themselves what kind of algorithms they support.

A solution would be to use https://github.com/rtyley/spongycastle as your security provider. This is a fully complete rename of Bouncy Castle specifically for use with Android. Vendors tend to strip down the Bouncy Castle implementations shipped with their phones.
